version: '2.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks: 
      - kanet
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    networks: 
      - kanet
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - .\vol\docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  kafka2:
    image: wurstmeister/kafka:latest
    networks: 
      - kanet
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_PORT: 9094
    volumes:
      - .\vol2\docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  kafka3:
    image: wurstmeister/kafka:latest
    networks: 
      - kanet
    ports:
      - "9096:9096"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_PORT: 9096
    volumes:
      - .\vol3\docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
networks:
  kanet:
    driver: bridge