apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 3
  serviceName: "kafka-service"
  selector:
    matchLabels:
      app: kafka
  volumeClaimTemplates:
    - metadata:
        name: log
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Mi
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:latest
        ports:
          - containerPort: 9092
        env:
          - name: "KAFKA_ADVERTISED_HOST_NAME"
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-service:2181
          - name: KAFKA_LOG_DIRS
            value: /var/log/kafka
        volumeMounts:
          - name: log
            mountPath: /var/log/kafka
      # volumes:
      #   - name: log 
          #emptyDir: {}
          # persistentVolumeClaim:
          #   claimName: pvc-persistent-cfg