apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper-service
spec:
  type: NodePort
  ports:
  - port: 2181
    targetPort: 2181
    nodePort: 30000
    protocol: TCP
  selector:
    app: zookeeper