apiVersion: v1
kind: Service
metadata:
  name: svc-springboot-nodeport
  labels:
    app: svc-springboot
spec:
  type: NodePort
  ports:
  - port: 30000
    targetPort: 30000
    nodePort: 30000
    protocol: TCP
  selector:
    app: springboot