apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: quanleminh/spring-boot-sample:1.0
        ports:
        - containerPort: 30000
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 30000
          initialDelaySeconds: 15